/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SimpleCalculatorPack;

/**
 *
 * @author emanuelmoreno
 */
public class MainCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MainCalculator
     */
    public MainCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SumaBtn = new javax.swing.JButton();
        RestaBtn = new javax.swing.JButton();
        MultBtn = new javax.swing.JButton();
        DivBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        Num1Txt = new javax.swing.JTextField();
        Num2Txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SumaBtn.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        SumaBtn.setText("+");
        SumaBtn.setToolTipText("");
        SumaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SumaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaBtnActionPerformed(evt);
            }
        });

        RestaBtn.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        RestaBtn.setText("-");
        RestaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaBtnActionPerformed(evt);
            }
        });

        MultBtn.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        MultBtn.setText("X");
        MultBtn.setToolTipText("");
        MultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultBtnActionPerformed(evt);
            }
        });

        DivBtn.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        DivBtn.setText("/");
        DivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivBtnActionPerformed(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        ClearBtn.setText("Borrar");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Inserta el primer numero");

        jLabel2.setText("Inserta el segundo numero");

        jLabel3.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SumaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RestaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(DivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(MultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Num1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Num2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Num1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SumaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        //Hacer que los textbox se cambien a 0
        Num1Txt.setText("0");
        Num2Txt.setText("0");
        TotalTxt.setText("0.0");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void SumaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaBtnActionPerformed
        //Tomar la data de los textboxs
        String num1 = Num1Txt.getText();
        String num2 = Num2Txt.getText();
        //Convertir la data a double
        double Num1 = Double.valueOf(num1);
        double Num2 = Double.valueOf(num2);
        //Ecuacion matematica
        double total = Num1+Num2;
        //Convertir ecuacion a String
        String Total = String.valueOf(total);
        //Imprimir en el textbox del resultado
        TotalTxt.setText(Total);
    }//GEN-LAST:event_SumaBtnActionPerformed

    private void RestaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaBtnActionPerformed
        //Tomar la data de los textboxs
        String num1 = Num1Txt.getText();
        String num2 = Num2Txt.getText();
        //Convertir la data a double
        double Num1 = Double.valueOf(num1);
        double Num2 = Double.valueOf(num2);
        //Ecuacion matematica
        double total = Num1-Num2;
        //Convertir ecuacion a String
        String Total = String.valueOf(total);
        //Imprimir en el textbox del resultado
        TotalTxt.setText(Total);
    }//GEN-LAST:event_RestaBtnActionPerformed

    private void DivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivBtnActionPerformed
        //Tomar la data de los textboxs
        String num1 = Num1Txt.getText();
        String num2 = Num2Txt.getText();
        //Convertir la data a double
        double Num1 = Double.valueOf(num1);
        double Num2 = Double.valueOf(num2);
        //Ecuacion matematica
        double total = Num1/Num2;
        //Convertir ecuacion a String
        String Total = String.valueOf(total);
        //Imprimir en el textbox del resultado
        TotalTxt.setText(Total);
    }//GEN-LAST:event_DivBtnActionPerformed

    private void MultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultBtnActionPerformed
        //Tomar la data de los textboxs
        String num1 = Num1Txt.getText();
        String num2 = Num2Txt.getText();
        //Convertir la data a double
        double Num1 = Double.valueOf(num1);
        double Num2 = Double.valueOf(num2);
        //Ecuacion matematica
        double total = Num1*Num2;
        //Convertir ecuacion a String
        String Total = String.valueOf(total);
        //Imprimir en el textbox del resultado
        TotalTxt.setText(Total);    }//GEN-LAST:event_MultBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton DivBtn;
    private javax.swing.JButton MultBtn;
    private javax.swing.JTextField Num1Txt;
    private javax.swing.JTextField Num2Txt;
    private javax.swing.JButton RestaBtn;
    private javax.swing.JButton SumaBtn;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
